<a href="https://colab.research.google.com/github/calzateu/Numerical_Analysis/blob/main/code/Sentiment_analysis/Our_Logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('Dataset-with-sentiments.csv')
data.head(5)

Unnamed: 0  ...                                      stop_comments
0           0  ...                       song hits different pain sad
1           1  ...                             adore talking comments
2           2  ...     used another love tears want sing song 'd love
3           3  ...  dear ana 're reading would like apologize stro...
4           4  ...  well men everyone broken heart welcome club sl...

[5 rows x 8 columns]

In [3]:
sum(data['stop_comments'].isnull())


0

In [4]:
data = data[data['stop_comments'].notnull()]

In [5]:
sum(data['stop_comments'].isnull())

0

In [6]:
data['pol_cat']

0       0
1       0
2       1
3       1
4       1
       ..
1068    0
1069    1
1070    1
1071    1
1072    1
Name: pol_cat, Length: 1073, dtype: int64

In [ ]:
data[data['pol_cat']==-1] = 0

In [ ]:
data['pol_cat']

0       0
1       0
2       1
3       0
4       1
       ..
1062    0
1063    1
1064    1
1065    0
1066    1
Name: pol_cat, Length: 1065, dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1065 entries, 0 to 1066
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Unnamed: 0     1065 non-null   int64  
 1   Video ID       1065 non-null   object 
 2   Comment ID     1065 non-null   object 
 3   comments       1065 non-null   object 
 4   polarity       1065 non-null   float64
 5   pol_cat        1065 non-null   int64  
 6   stop_comments  1065 non-null   object 
dtypes: float64(1), int64(2), object(4)
memory usage: 66.6+ KB


In [9]:
data['stop_comments'] = data[['stop_comments']].astype(str)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train,X_test,y_train,y_test = train_test_split(data['stop_comments'],data['pol_cat'],test_size = 0.2,random_state = 324)

In [12]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer 
vect = CountVectorizer()
tf_train = vect.fit_transform(X_train)
tf_test = vect.transform(X_test)

In [13]:
tf_train = tf_train.toarray()
tf_test = tf_test.toarray()

In [17]:
# Importing libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings( "ignore" )

# to compare our model's accuracy with sklearn model
from sklearn.linear_model import LogisticRegression
# Logistic Regression
class LogitRegression() :
    def __init__( self, learning_rate, iterations ) :        
        self.learning_rate = learning_rate        
        self.iterations = iterations
          
    # Function for model training    
    def fit( self, X, Y ) :        
        # no_of_training_examples, no_of_features        
        self.m, self.n = X.shape        
        # weight initialization        
        self.W = np.zeros( self.n )        
        self.b = 0        
        self.X = X        
        self.Y = Y
          
        # gradient descent learning
                  
        for i in range( self.iterations ) :            
            self.update_weights()            
        return self
      
    # Helper function to update weights in gradient descent
      
    def update_weights( self ) :           
        A = 1 / ( 1 + np.exp( - ( self.X.dot( self.W ) + self.b ) ) )
          
        # calculate gradients        
        tmp = ( A - self.Y.T )        
        tmp = np.reshape( tmp, self.m )        
        dW = np.dot( self.X.T, tmp ) / self.m
        db = np.sum( tmp ) / self.m 
          
        # update weights    
        self.W = self.W - self.learning_rate * dW    
        self.b = self.b - self.learning_rate * db
          
        return self

    # Hypothetical function  h( x ) 
      
    def predict( self, X ) :    
        Z = 1 / ( 1 + np.exp( - ( X.dot( self.W ) + self.b ) ) )        
        Y = np.where( Z > 0.5, 1, 0 )        
        return Y


## Using median intead of mean

In [30]:
# Importing libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings( "ignore" )

# to compare our model's accuracy with sklearn model
from sklearn.linear_model import LogisticRegression
# Logistic Regression
class LogitRegression() :
    def __init__( self, learning_rate, iterations ) :        
        self.learning_rate = learning_rate        
        self.iterations = iterations
          
    # Function for model training    
    def fit( self, X, Y ) :        
        # no_of_training_examples, no_of_features        
        self.m, self.n = X.shape        
        # weight initialization        
        self.W = np.zeros( self.n )        
        self.b = 0        
        self.X = X        
        self.Y = Y
          
        # gradient descent learning
                  
        for i in range( self.iterations ) :            
            self.update_weights()            
        return self
      
    # Helper function to update weights in gradient descent
      
    def update_weights( self ) :           
        A = 1 / ( 1 + np.exp( - ( self.X.dot( self.W ) + self.b ) ) )
          
        # calculate gradients        
        tmp = ( A - self.Y.T )        
        tmp = np.reshape( tmp, self.m )        
        #dW = np.dot( self.X.T, tmp ) / self.m
        dW = np.zeros(len(tmp))
        for i in range(len(tmp)):
          #print(self.X.T[i])
          #print(tmp[i])
          dW[i] = self.X.T[i]*tmp
        dW = np.median( dW )
        db = np.median( tmp )

        # update weights    
        self.W = self.W - self.learning_rate * dW    
        self.b = self.b - self.learning_rate * db
          
        return self
      
    # Hypothetical function  h( x ) 

    def predict( self, X ) :    
        Z = 1 / ( 1 + np.exp( - ( X.dot( self.W ) + self.b ) ) )        
        Y = np.where( Z > 0.5, 1, 0 )        
        return Y

In [31]:
# Driver code

def main() :
    # Model training    
    model = LogitRegression( learning_rate = 1, iterations = 10000 )
      
    model.fit( tf_train, y_train )    
    model1 = LogisticRegression()    
    model1.fit( tf_train, y_train)

    # Prediction on test set
    Y_pred = model.predict( tf_test )    
    Y_pred1 = model1.predict( tf_test )
    
    # measure performance    
    correctly_classified = 0    
    correctly_classified1 = 0


    Y_test = y_test.to_xarray()
    
    # counter    
    count1 = 0    
    for count in range( np.size( Y_pred ) ) :  
        
        if Y_test[count] == Y_pred[count] :            
            correctly_classified = correctly_classified + 1
          
        if Y_test[count] == Y_pred1[count] :            
            correctly_classified1 = correctly_classified1 + 1
              
        count1 = count1 + 1
          
    print( "Accuracy on test set by our model       :  ", ( 
      correctly_classified / count1 ) * 100 )
    print( "Accuracy on test set by sklearn model   :  ", ( 
      correctly_classified1 / count1 ) * 100 )
  
  
if __name__ == "__main__" :     
    main()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


ValueError: ignored

In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])